### ISSUE TITLE
[feature/netcore] SocketException when attempting basic example

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1165]
Getting exception as follows:

**SocketException**: The attempted operation is not supported for the type of object referenced
`System.Net.IPAddress.get_Address()`

**Stack Trace**:
```
    System.Net.IPAddress.get_Address()
    Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter<TDeclaringType, TValue>(Func<TDeclaringType, TValue> getter, object target)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, string key, object model)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, string key, object model)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, string key, object model)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, string key, object model)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
    Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, string key, object model)
    Microsoft.AspNetCore.Mvc.Internal.DefaultObjectValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, string prefix, object model)
    Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder+<BindModelAsync>d__6.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider+<>c__DisplayClass0_0+<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

Link to test project: [OData_Test](https://github.com/gordon-matt/OData_Test)
To see the problem, just run it and browse to: **/odata/PublicUserApi**

**Comment by robward-ms** [comment]
@gordon-matt - I tracked the issue down to lines 44 and 56 of ODataQueryOptions.cs: https://github.com/OData/WebApi/blob/feature/netcore/src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs

OData WebApi properly binds the ODataQueryOptions instance. Then, it looks like AspNetCore calls on public property getters and validates all objects. It's pretty unhappy to see an HttpRequest on the object. 

Once I comment out 44 & 56, model validation passes and it calls the controller, at which point the code fails on my machine since I don't have the DB.

**Comment by gordon-matt** [comment]
@robward-ms Thanks. I noticed an update on myget and tried it, but it's the same error.. so I guess that one wasn't the fix. When can I expect the fix to be deployed to myget?

**Comment by robward-ms** [comment]
@gordon-matt - If you got it tonight, would you test over the weekend?

**Comment by robward-ms** [comment]
Fixed in the Nightly build that is newer than 201712151325 (2017-12-15 13:25)

**Comment by gordon-matt** [comment]
@robward-ms Thanks, but I already tried that version and it's not fixed. I have the exact same error still. Could you please check again? Thanks

**Comment by robward-ms** [comment]
Yep, you need the Nightly build that is **newer** than 201712151325 (2017-12-15 13:25). I wrote the comment before the build had dropped not knowing it's final name. That build failed but one just finished, you need 201712180820.

**Comment by techniq** [comment]
@robward-ms works for me using 7.0.0-Nightly201712181325 to consume queryOptions as a parameter.

Trying to return an ActionResult is giving `No output formatter was found for content type '' to write the response.`

```c#
        [HttpGet]
        public IActionResult Export(ODataQueryOptions<Employee> queryOptions)
        {
            var query = queryOptions.ApplyTo(DbContext.Set<Employee>()) as IQueryable<Employee>;
            var exportQuery = query.Select(e => new EmployeeExport { Name = e.FullName }).Take(5);
            return Ok(exportQuery);
        }
```

This is an arbitrary example.  Typically I'm returning a custom action result (for example, an excel download).  I can log a new issue once I have a better example and have worked through it.

**Comment by robward-ms** [comment]
@techniq - An example and new issue for the bug would be great, thanks!

**Comment by gordon-matt** [comment]
It works! Thanks @robward-ms . I would close the issue now myself, but it seems @techniq needs to either be answered here or open a separate issue first. Thanks for the fix!

**Comment by robward-ms** [comment]
@techniq - Can you file a separate issue for this? FYI, I'm seeing this work in the latest code that I'm about to put in a PR.

**Comment by techniq** [comment]
@robward-ms I'll try to get one submitted soon, but it might be sometime next week (and you might have the PR merged before then).  My current project is my first on ASP.NET Core so I've been hesitant when I've run into issues if they're due to things being different on ASP.NET Core vs OData 7.  Feel free to close this and I'll submit an issue soon.
