### ISSUE TITLE
Unable to get batch response in json format

### ISSUE THREAD

**Issue by igor-moskvitin** [OData/WebApi#1532]
*Unable to get batch response in json format*

### Assemblies affected

*OData WebApi lib 7.0*

### Reproduce steps

For AspNetCoreODataSample.Web:
```
app.UseODataBatching();
...
app.UseMvc(builder =>
            {
                builder.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
                builder.MapODataServiceRoute("odata1", "efcore", model, new DefaultODataBatchHandler());
                builder.MapODataServiceRoute("odata2", "inmem", model);
                builder.MapODataServiceRoute("odata3", "composite", EdmModelBuilder.GetCompositeModel());
            });
```

```
POST /efcore/$batch HTTP/1.1
Host: localhost:5912
Content-Type: application/json
{
	"requests": 
	[
		{
			"id" : "1",
			"method": "GET",
			"url" : "/Movies(1)"
		}
	]
}
```

### Expected result

Result as JSON

### Actual result

```
--batchresponse_dd790896-923f-4116-b4c3-35bda5ab7767
Content-Type: application/http
Content-Transfer-Encoding: binary
HTTP/1.1 404 Not Found
--batchresponse_dd790896-923f-4116-b4c3-35bda5ab7767--
```

**Comment by biaol-odata** [comment]
@igor-moskvitin The PR #1536 above should fix the issue. Thanks for reporting.

**Comment by biaol-odata** [comment]
PR has been Merged. This issue can be closed now.

**Comment by igor-moskvitin** [comment]
@biaol-odata excuse me, but PR doesnt fix issue, or maybe i do something wrong:
```
POST /efcore/$batch HTTP/1.1
Host: localhost:5913
Content-Type: application/json
Cache-Control: no-cache

{
	"requests": 
	[
		{
			"id" : "1",
			"method": "GET",
			"url" : "movies(1)",
			"headers": {"accept": "application/json"}
		}
	]
}
```
and getting that:
```
Content-Type →multipart/mixed;boundary=batchresponse_9949d446-5f86-402e-b48c-05cc753e679e
Date →Thu, 19 Jul 2018 08:33:54 GMT
OData-Version →4.0
Server →Kestrel
Transfer-Encoding →chunked

--batchresponse_9949d446-5f86-402e-b48c-05cc753e679e
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

{"@odata.context":"http://localhost:5913/efcore/$metadata#Movies/$entity","ID":1,"Title":"Conan","ReleaseDate":"2017-03-03T00:00:00+07:00","Genre":"Comedy","Price":1.99}
--batchresponse_9949d446-5f86-402e-b48c-05cc753e679e--


```

**Comment by igor-moskvitin** [comment]
Find out that need to use `Accept: application/json` and it works now
