### ISSUE TITLE
v5.6: Created response can't process the un-type object

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#154]
public IHttpActionResult Post(EdmEntityObject customer)  
{  

    
    
            return Created(customer);

}  
  
the response Created Fails with the following exception:  
500 Internal Error:  
Inner Exception:  
Cannot find the entity type 'System.Web.OData.EdmEntityObject' in the model.  
  
the exception throws at:  
..\Src\OData\src\System.Web.OData\OData\Results\ResultHelpers.cs  
  
private static IEdmEntityTypeReference GetEntityType(IEdmModel model, object
entity)  

    
    
        {
            Type entityType = entity.GetType();
            IEdmTypeReference edmType = model.GetEdmTypeReference(entityType);
            if (edmType == null)
            {
                throw Error.InvalidOperation(SRResources.EntityTypeNotInModel, entityType.FullName);
            }
            if (!edmType.IsEntity())
            {
                throw Error.InvalidOperation(SRResources.TypeMustBeEntity, edmType.FullName());
            }
    
            return edmType.AsEntity();
        }
    

Does we should take care the created response for un-type object  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2135](http://aspnetwebstack.codeplex.com/workitem/2135)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 12, 2014 at 5:08 AM
**Reported by:**	xuzhg
**Updated on:**	Tue at 7:37 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 15:37:43 UTC*, **cysu** commented:

Suggest fix.

**Comment by xuzhg** [comment]
It should be fixed. See: https://github.com/OData/WebApi/blob/master/OData/test/UnitTest/System.Web.OData.Test/OData/OpenEntityTypeTest.cs#L583-L653

**Comment by AviaW** [comment]
Hello, 
I'm developing an OData service and still have this problem with version 5.7 of OData Lib.
In the OpenEntityTypeTest.cs above the response to the Post request is HTTP 200 OK and doesn't contain a Location header.
In the OData specification
(http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398326)
it says:
11.4.2 Create an Entity
.....
"Upon successful completion, the response MUST contain a Location header that contains the edit URL or read URL of the created entity.
Upon successful completion the service MUST respond with either 201 Created, or 204 No Content if the request included a return Prefer header with a value of return=minimal."
Am I wrong?
Thanks.

**Comment by AviaW** [comment]
Hi,
I did the following change to the code in order to workaround the problem. It works for me:

private static IEdmEntityTypeReference GetEntityType(IEdmModel model, object entity)
        {            
            Type entityType = entity.GetType();
            **IEdmTypeReference edmType = null;
            if (entity is EdmEntityObject)
                edmType = ((EdmEntityObject)entity).GetEdmType();
            else
                edmType = model.GetEdmTypeReference(entityType);**
            if (edmType == null)
            {
                throw Error.InvalidOperation(SRResources.EntityTypeNotInModel, entityType.FullName);
            }
            if (!edmType.IsEntity())
            {
                throw Error.InvalidOperation(SRResources.TypeMustBeEntity, edmType.FullName());
            }

            return edmType.AsEntity();
        }
