### ISSUE TITLE
High CPU usage after updating to Microsoft.AspNet.OData 7.6.1

### ISSUE THREAD

**Issue by RyanMarcotte** [OData/WebApi#2731]
I updated from `Microsoft.AspNet.OData` from 7.5.14 to 7.6.1 and the new package version caused significant slowdown for our website deployed to Azure App Service.  After analyzing a few CPU traces, I was able to drill down and find this:

![image](https://user-images.githubusercontent.com/1458084/204598103-d7307b3e-006d-4541-a421-9746ed624ff2.png)

Downgrading from 7.6.1 back to 7.5.14 fixed the performance problem.  Instead of using `SingleOrDefault`, use some cached lookup instead?

### Assemblies affected

`Microsoft.AspNet.OData` 7.6.1

**Comment by ElizabethOkerio** [comment]
@RyanMarcotte this was fixed by this: https://github.com/OData/WebApi/pull/2769. Feel free to reopen in case of anything.

**Comment by RyanMarcotte** [comment]
This is still an issue after we updated to 7.6.5.  We will be downgrading back to 7.5.14 until this is fixed.

![image](https://github.com/OData/WebApi/assets/1458084/7ff7416d-9d0e-4ea9-8792-aee89dc5e4a1)
