### ISSUE TITLE
Support recursive nullable complex types

### ISSUE THREAD

**Issue by Casimodo72** [OData/WebApi#437]
Hi,

I'm getting the following exception when trying to build a recursive complex type with the ODataConventionModelBuilder.

"The complex type 'DataAttachment' has a reference to itself through the property 'Items'. A recursive loop of complex types is not allowed.
Parametername: propertyInfo"

According to this post the issue may already be known (https://groups.google.com/forum/#!topic/odata-discussion/zGP2wDYUmaE).
Support for recursive complex types would be really great, as I'm trying to implement a flexible multipurpose container for binary attachments.

Scenario:

``` csharp

builder.ComplexType<DataAttachment>();

public sealed partial class DataAttachment
{
    public DataAttachment()
    {
        Header = new Dictionary<string, string>();
        Properties = new Dictionary<string, object>();
        Items = new Collection<DataAttachment>();
        BinaryData = new byte[0];
    }
    public Dictionary<string, string> Header { get; set; }
    public Dictionary<string, object> Properties { get; set; }
    public Collection<DataAttachment> Items { get; set; }
    public string Data { get; set; }
    public byte[] BinaryData { get; set; }
}
```

Stack trace:
bei System.Web.OData.Builder.StructuralTypeConfiguration.AddCollectionProperty(PropertyInfo propertyInfo)
bei System.Web.OData.Builder.ODataConventionModelBuilder.MapStructuralProperty(StructuralTypeConfiguration type, PropertyInfo property, PropertyKind propertyKind, Boolean isCollection)
bei System.Web.OData.Builder.ODataConventionModelBuilder.MapComplexType(ComplexTypeConfiguration complexType)
bei System.Web.OData.Builder.ODataConventionModelBuilder.MapType(StructuralTypeConfiguration edmType)
bei System.Web.OData.Builder.ODataConventionModelBuilder.MapTypes()
bei System.Web.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
bei Ga.Web.Init.ODataConfig.Configure(HttpConfiguration config) in C:\Dev\Projects\XYZ\Ga\src\Ga.Web\AppStartup\ODataConfig.cs

I'm using:
Microsoft.AspNet.OData 5.7.0-beta-150716-Nightly (and the latest nightly ODataLib packages)
.NET 4.5.2
VS 2015 RC

Regards,
Kasimier Buchcik

**Comment by congysu** [comment]
Complex type value is auto expanded by default.

**Comment by brjohnstmsft** [comment]
@robward-ms This issue seems to be a duplicate of https://github.com/OData/WebApi/issues/930 Also, both issues have PRs that were closed, but it isn't clear why. Any plans to follow up on this? This issue is a blocker for Complex Types support in Azure Search.

**Comment by robward-ms** [comment]
Looks like this was fixed in #977 and is available in WebApi 6.1. I verified the fix using the test case above.

**Comment by brjohnstmsft** [comment]
This was not completely fixed. See this issue for broader context: https://github.com/OData/WebApi/issues/1248
