### ISSUE TITLE
$orderby with duplicate property in odata v4 failed.

### ISSUE THREAD

**Issue by janvanderhaegen** [OData/WebApi#630]
This issue was supposedly fixed in #376 , but the fix does not cover all use cases.
For example
Customer > City(string)
Customer > Address(Address) > City(string)
Customer > WorkAddress(Address) > City(string)

Thanks to the fix in #376, one can order by Customer/City, Customer/Address/City without exception (they are different IEdmProperties)

However, one cannot order by Customer/Address/City, Customer/WorkAddress/City (they are the 'same' IEdmProperty).

**Comment by VikingsFan** [comment]
@janvanderhaegen Thanks! Would you like to submit a PR for this issue :)

**Comment by mirsking** [comment]
This issue is already fixed by PR #799 .

**Comment by mirsking** [comment]
This issue is already fixed by PR #799 .

**Comment by Malyngo** [comment]
Is this fix in version 6.0.0? I just updated, but still see that issue.

**Comment by thelongshot** [comment]
As Malyngo says above, this bug still exists in 6.0.0.  Please reopen.
