### ISSUE TITLE
$orderBy using the same property from two instances of same class type fails

### ISSUE THREAD

**Issue by kbarkhausen-campusmgmt** [OData/WebApi#820]
This is similar to issue #376 which is closed.
The previous issue was titled: "$orderBy with duplicate property in odata v4".

When performing a query where $orderby points to two properties of the same class type (i.e. Address) and there is a need to sort by the same property name on both separate instances of the same class then the OData query throws an error.

For example:

http://(host)/API/Customers?$expand=BillingAddress,ShippingAddress &$orderby=BillingAddress/City,ShippingAddress/City

Then the following exception is thrown:

Duplicate property named 'City' is not supported in '$orderby'.

### Reproduce steps
You can review the unit test I added to my fork of WebApi. 

The test is named:
"ApplyTo_NestedExpandedPropertiesOfSameType_UsingSamePropertyNameToSort_Succeeds"
This demonstrates the issue being reported.

### Expected result
It should allow for the capability to sort by the properties since they belong to different instances of the same type.

**Comment by VikingsFan** [comment]
@kbarkhausen-campusmgmt can you try 6.0 that this issue is fixed?

**Comment by kbarkhausen-campusmgmt** [comment]
The issue remains in 6.0. I forked the latest version of the WebApi code yesterday (which includes the latest v6.0) and I added a unit test that demonstrates that the error still remains in the latest version of OData.

You can see the unit test that demonstrates this error in my forked repository:

**Comment by kbarkhausen-campusmgmt** [comment]
The issue remains in 6.0. I forked the latest version of the WebApi code yesterday (which includes the latest v6.0) and I added a unit test that demonstrates that the error still remains in the latest version of OData.

You can see the unit test that demonstrates this error in my forked repository:
https://github.com/kbarkhausen-campusmgmt/WebApi

You can see the details of the unit test here:
https://github.com/kbarkhausen-campusmgmt/WebApi/commit/c48ee58728655ec5760daaff246c6e5e950e639d

It demonstrates that when I try to sort by "BillingAddress/City,ShippingAddress/City" the error occurs. 

I have identified that the error only happens when you try to sort by the same property of the same class type that are used under different navigational property paths.

**Comment by kbarkhausen-campusmgmt** [comment]
Fan and OData team:

The issue remains in 6.0. I forked the latest version of the WebApi code yesterday (which includes the latest v6.0) and I added a unit test that demonstrates that the error still remains in the latest version of OData.
You can see the unit test that demonstrates this error in my forked repository:
https://github.com/kbarkhausen-campusmgmt/WebApi
You can see the details of the unit test here:
kbarkhausen-campusmgmt@c48ee58<https://github.com/kbarkhausen-campusmgmt/WebApi/commit/c48ee58728655ec5760daaff246c6e5e950e639d>
It demonstrates that when I try to sort by "BillingAddress/City,ShippingAddress/City" the error occurs.
I have identified that the error only happens when you try to sort by the same property of the same class type that are used under different navigational property paths.

Klaus Barkhausen
Software Architect (.NET)

Campus Management Corp.
777 Yamato Road
Boca Raton, FL 33431
Cell: +1 <786.390.8337>
Visit: www.campusmanagement.com<http://www.campusmanagement.com/>

[Description: Description: Description: cid:image001.png@01CDD3A3.EEBF0B00]<http://www.facebook.com/#!/pages/Campus-Management-Corp/307093670261?ref=mf> [Description: Description: Description: cid:image002.png@01CDD3A3.EEBF0B00] <http://twitter.com/CampusMgmt>  [Description: Description: Description: Description: cid:image003.png@01CDD3A3.EEBF0B00] <http://www.linkedin.com/company/campus-management-corp>  [Description: Description: Description: cid:image004.png@01CDD3A3.EEBF0B00] <http://www.youtube.com/user/campusvue>

Join us!
EDUCAUSE Annual Conference 2015
October 27 – 30, 2015 | Indianapolis, IN
Visit us in booth #1809<http://www.campusmanagement.com/EN-US/newsandevents/events/EDUCAUSE/Pages/default.aspx>

**Comment by VikingsFan** [comment]
@kbarkhausen-campusmgmt the branch is OData60

**Comment by kbarkhausen-campusmgmt** [comment]
Version 6.0 contains the fix - but how do we upgrade?

We have a solution that uses both Microsoft.AspNet.OData and Microsoft.OData.Client packages.

Their dependencies are as follows:
Microsoft.AspNet.OData 6.0.0  -> Microsoft.OData.Core (>= 7.0.0 && < 8.0.0) 
Microsoft.OData.Client 6.15.0 -> Microsoft.OData.Core (= 6.15.0) 

If I try to install version 6.0, I am unable to install Microsoft.OData.Client due to the following error:
Microsoft.OData.Core 7.0.0 is not compatible with Microsoft.OData.Client 6.15.0

Is there an update to Microsoft.OData.Client to be expected soon?

**Comment by kbarkhausen-campusmgmt** [comment]
Closed since the problem I reported in my last entry is a different issue. I created a new issue to that address that separately.
